---
title: "à propos de ce site"
author: "PSLèbre"
output: html_document

---
```{r setup, include=F ,echo=FALSE, cache=F}
library(BAMMtools)
library(kableExtra)
library(flexdashboard)
library(gghighlight)
library(highcharter)
library(janitor)
library(DT)
library(fontawesome)
library(formattable)
library(rgdal)
library(osrm)
library(fontawesome)
library(leafpop)
library(leaflet.providers) 
library(readxl)
library(leaflet.minicharts)
library(leaflet)
library(leaflegend)
library(leaflet.extras2)
library(tidyverse)
source("librairies.R")

#rmarkdown::render_site(encoding = 'UTF-8')

depbfc <- c('21','25','39','58','70','71','89','90')

thm <- hc_theme_merge(
  hc_theme_gridlight( yAxis = list(
        title = list(
          style = list(
            textTransform = "normal") ) ) ),
  hc_theme(
#    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  ) 
)

# Option de chunk
knitr::opts_chunk$set(
 fig.width = 6,
 fig.asp = 0.8,
 out.width = "80%"
)
```


#<style>
#.active {
#  font-size:25px;
#}
#</style>

## Fonctionnement

#### Pour consulter les chiffres clés depuis votre poste, téléchargez le fichier zip ***\_site*** et décompressez le à l'endroit de votre choix. Ouvrez ensuite le fichier [**DRAJESBFC.html**l]{.ul}, il fait le lien vers les autres documents du dossier (doit s'ouvrir dans un navigateur type Firefox).

## Contenu

Ce document se présente comme un site interactif et dynamique. Il balaie l’ensemble des thèmes de la DRAJES et propose des
comparaisons régionales, départementales et infradépartementales lorsque cela est possible. Il s’appuie sur des bases de données open
source et sur les données de cadrage fournies par la MEDES (mission études, données et enquêtes statistiques de l’Injep).  

Le bandeau du haut présente l’échelon territorial (région, département, EPCI et bassins de vie), et, selon les sujets, des pages
supplémentaires. On y trouve également une rubrique « Pour en savoir plus » qui pointe vers d’autres sites externes et « Navigation » qui permet de changer de page sans passer par « Accueil ».  

Dans chaque page, un bloc « Données générales » apporte quelques informations générales à retenir.
Les autres blocs présentent les données selon un système d’onglets explicites : tableaux de données, graphiques de comparaisons et cartes. Les cartes sont dynamiques et cliquables, la plupart des graphiques également.  

Lors de votre navigation, vous pouvez faire remonter vos remarques ou tout problème de mise en page (faute de frappe, source illisible ou manquante, proposition d’amélioration...) sur mon mail : pierre-stephane.lebre@ac-dijon.fr  
